### ISSUE TITLE
Thank you & Question(s)

### ISSUE THREAD

**Issue by ghost** [tom-auger/secretbox#1]
Hello @tom-auger and thank you for publishing this. 

I'm currently investigating the suitability of the library for my cross platform .NET standard based apps. It seems like a good fit, but there are a couple of questions I can't answer myself. 

If you don't mind:

1. Are there any plans on adding **async** support (`Task<T>` instead of `T` and `Task` instead of `void` returns)  or better yet default everything to **async** ?
2. Are there any plans on adding [deterministic random numbers](https://github.com/jedisct1/libhydrogen/wiki/Random-numbers#deterministic-random-numbers) support like **libhydrogen** has or at least allowing the plugging of custom **RNG** engines to support this scenario ?
3. Would you use the library in production yourself ? :)

Regards.

**Comment by taugr** [comment]
Hi,

Thanks for your interest!

1. I don't plan to add async methods, unless there is a compelling use case for them. The current API is best suited for encrypting small amounts of data in memory, so typically will not be a long running operation. To process large amounts of data it's best to encrypt it in chunks, so implementing something like the [CryptoStream](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.cryptostream?view=netframework-4.8) with async methods, on top of the SecretBox API would probably be the way to go. 

2. I didn't add an API for random number generation as SecretBox simply uses the [RNGCryptoServiceProvider](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rngcryptoserviceprovider?view=netframework-4.8) for generating the key and nonce. The [System.Random](https://docs.microsoft.com/en-us/dotnet/api/system.random.-ctor?view=netframework-4.8#System_Random__ctor_System_Int32_) class would be best for deterministic keys, however I'm less keen on making the random number generation customizable as one of the main goals is to make the library hard to mis-use, and it could be hard to spot if your code was using a SecretBox with a deterministic RNG. If you're thinking of doing this for testing then instead I would recommend creating a mock SecretBox that implements `ISecretBox` and returns deterministic results that way.

3. Yes, to the same degree that I would use libhydrogen! I'm not aware of other projects using it in production, but I would very much it to be. Bear in mind the code hasn't been audited like some other mainstream crypto libraries, so consider whether it meets your security requirements.

Regards,
Tom

**Comment by ghost** [comment]
Thanks @tom-auger . Closing this.
